Repository SaraswatGit/PlanZap, pull requests merged in 2022-02, with the labels that each got.

#10 Added the feature to match password and confirm password
  src/loginpage.js
Labels: JWOC, easy

#16 fix: routing path of Tasks and Progress page from /Calendar to /TasksandProgress
  src/App.js
Labels: JWOC, easy

#17 Changed cursor to become pointer when hovering over text elements in bottom part of the tasks and progress page #13 issue no 13 JWOC
  src/CSSComponents/calendarstyle.css
Labels: JWOC, easy

#20 Issue6
  src/CSSComponents/App.css
  src/LoadingScreen.jsx
Labels: JWOC, easy

#21 Switching to Landscape mode when width is less than 600 px
  package-lock.json
  src/CSSComponents/window.css
  src/Context/curved_arrow.png
  src/Context/—Pngtree—mobile frame png image and_6631525.png
  src/index.js
  src/window.js
Labels: JWOC, Medium

#22 I have improved the documentation (README.md) as per the issue #5
  README.md
Labels: JWOC, easy

#23 Improving the Login and Registration Features and UI . #3
  package-lock.json
  package.json
  src/CSSComponents/Vector Image.jpg
  src/CSSComponents/loginpage.css
  src/loginpage.js
Labels: JWOC, Hard

#24 popup aded
  package-lock.json
  package.json
  src/CSSComponents/calendarstyle.css
  src/calendar.js
Labels: JWOC, Medium

#32 Fixed the issue #15, a diary entry when added/updated, is shown on screen
  src/diary.jsx
Labels: JWOC, Medium

#33 aded loading
  src/calendar.js
  src/ideas.js
  src/movies.jsx
Labels: JWOC, Medium

#35 Modified CSS of delete popup
  src/CSSComponents/delete.css
  src/calendar.js
  src/ideas.js
  src/movies.jsx
Labels: JWOC, easy

#37 Modified delete button in movies page
  src/CSSComponents/movies.css
  src/movies.jsx
Labels: JWOC, Medium

#42 Confetti celebration on task finish
  package-lock.json
  package.json
  src/App.js
  src/ConfettiCeleb.js
  src/calendar.js
Labels: JWOC, Medium

#43 Modified modals and buttons
  src/CSSComponents/diary.css
  src/CSSComponents/movies.css
  src/diary.jsx
  src/ideas.js
  src/movies.jsx
Labels: JWOC, Medium

#45 On delete task, no confetti added.
  src/calendar.js
Labels: JWOC, easy

#51 last quote does not disappear if no chnages are made
  src/App.js
Labels: JWOC, Medium

#54 Updated sort task functionality
  package-lock.json
  src/CSSComponents/calendarstyle.css
  src/calendar.js
Labels: JWOC, Hard

#56 Restricting the user to register multiple times with same email id
  index.js
Labels: JWOC, Medium

#59 Added maintenance page
  src/App.js
  src/CSSComponents/maintenance.svg
  src/ideas.js
  src/loginpage.js
  src/movies.jsx
Labels: JWOC, Medium

#61 Documentaion Updated
  README.md
Labels: JWOC, Medium

#72 Added sort functionality to IMDb rating
  src/CSSComponents/movies.css
  src/movies.jsx
Labels: JWOC, Medium

#71 popup on first time visit
  src/App.js
Labels: JWOC, Medium

#73 fix: Updated the styling of New Quote Modal
  src/App.js
  src/CSSComponents/App.css
Labels: JWOC, easy

#74 Added the books section
  src/App.js
  src/CSSComponents/booksToRead.css
  src/booksToRead.jsx
Labels: JWOC, Medium

#76 fix: Updated How to use UI
  src/HowToUse.js
  src/howtouse.css
  src/images/diary4.png
  src/images/diary5.png
  src/images/dtask4.png
  src/images/movie5.png
  src/images/movie6.png
  src/images/note5.png
  src/images/right-arrow.png
  src/images/stask2.png
  src/images/stask3.png
  src/images/task2.png
  src/images/task3.png
  src/images/task4.png
Labels: JWOC, Medium

#75 Improved Responsiveness
  src/CSSComponents/calendarstyle.css
  src/calendar.js
Labels: JWOC, Medium

#79 Login Page bug resolved
  src/CSSComponents/loginpage.css
  src/loginpage.js
Labels: JWOC, easy

#81 fix: Warnings on VS code/ Console
  src/App.js
  src/HowToUse.js
  src/booksToRead.jsx
  src/calendar.js
  src/diary.jsx
  src/ideas.js
  src/index.js
  src/loginpage.js
  src/movies.jsx
  src/window.js
Labels: JWOC, Medium

#82 Login page
  src/CSSComponents/loginpage.css
  src/loginpage.js
Labels: JWOC, Medium

#84 Fixed UI errors
  src/CSSComponents/App.css
  src/CSSComponents/booksToRead.css
  src/CSSComponents/movies.css
  src/booksToRead.jsx
  src/diary.jsx
Labels: JWOC, Medium

#85 inline edit for idea page
  src/CSSComponents/ideas.css
  src/idea.js
  src/ideas.js
Labels: JWOC, Hard

#86 PasswordStrengthMeter added on registration
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/PasswordStrengthMeter.js
  src/loginpage.js
  yarn.lock
Labels: JWOC, easy
