Repository SaraswatGit/PlanZap, pull requests merged in 2022-03, with the labels that each got.

#99 On new user registering, he is redirected to calendar page
  Frontend/src/loginpage.js
  Frontend/yarn.lock
Labels: JWOC, Medium

#100 Update README.md
  README.md
Labels: JWOC, easy

#112 Updated readme
  README.md
Labels: GSSoC'22, Level-2

#114 Spinner loader added
  Frontend/src/HowToUse.js
  Frontend/src/images/spinner.gif
Labels: GSSoC'22, Level-2

#115 Fixed issue in adding task #110
  Frontend/src/calendar.js
Labels: GSSoC'22, Level-2

#119 Revert "Made changes in frontend login UI"
  Backend/package.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.js
  Frontend/src/AppLogin.css
  Frontend/src/CSSComponents/AppLogin.css
  Frontend/src/CSSComponents/loginpage.css
  Frontend/src/loginpage.js
Labels: JWOC, easy

#126 removed loading screen
  .gitignore
  Frontend/src/calendar.js
  Frontend/src/ideas.js
  Frontend/src/movies.jsx
Labels: JWOC, Medium

#129 Diary view called on selecting a date
  Frontend/src/diary.jsx
Labels: GSSoC'22, Level-2

#133 Fixed diary details as per date display issue
  Frontend/src/CSSComponents/loginpage.css
  Frontend/src/diary.jsx
Labels: GSSoC'22, Level-2

#135 Removed yarn.lock
  Backend/package-lock.json
  Frontend/package-lock.json
  Frontend/yarn.lock
Labels: GSSoC'22, Level-1

#107 Backend Folder Structure: Added routers folders for each type of endpoint
  Backend/db.js
  Backend/index.js
  Backend/routers/calendar.js
  Backend/routers/diary.js
  Backend/routers/movies.js
  Backend/routers/notes.js
Labels: JWOC, Hard

#146 cross aligned
  Frontend/src/CSSComponents/calendarstyle.css
Labels: JWOC, Medium

#150 Added styling and hover effects for modals of movie page
  Frontend/src/CSSComponents/movies.css
  Frontend/src/movies.jsx
Labels: GSSoC'22, Level-2

#154 added circuler loader
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
Labels: JWOC, Medium

#165 Readme update
  README.md
Labels: GSSoC'22, Level-1

#163 commented "howtouse" part
  Frontend/src/App.js
Labels: GSSoC'22, Level-1

#169 Removed cross button
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
  Frontend/src/diary.jsx
Labels: JWOC, easy

#172 Modified the CSS of Task Cards
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
Labels: JWOC, Medium

#173 bottom bar added while fetching data
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
Labels: JWOC, easy

#166 Fixed the size of text area during editing note description
  Frontend/src/idea.js
Labels: GSSoC'22, Level-2

#177 deleted cross icon
  Frontend/src/calendar.js
  Frontend/src/idea.js
  Frontend/src/movies.jsx
Labels: JWOC, Medium

#178 issue: #143 fixed
  Frontend/src/CSSComponents/calendarstyle.css
Labels: GSSoC'22, Level-2

#176 issue-140 solved:
  Frontend/src/CSSComponents/calendarstyle.css
Labels: GSSoC'22, Level-2

#182 hover effect adde
  Frontend/src/CSSComponents/App.css
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/CSSComponents/ideas.css
  Frontend/src/CSSComponents/movies.css
  Frontend/src/calendar.js
  Frontend/src/idea.js
  Frontend/src/ideas.js
  Frontend/src/movies.jsx
Labels: JWOC, easy

#184 added cancel button
  Frontend/src/CSSComponents/ideas.css
  Frontend/src/idea.js
Labels: JWOC, Medium

#185 How to Use Updated
  Frontend/src/HowToUse.js
  Frontend/src/howtouse.css
Labels: JWOC, Medium

#186 Added Logos
  Frontend/src/images/PlanZap Logo 1.svg
  Frontend/src/images/PlanZap Logo 2.svg
  Frontend/src/images/PlanZap Logo 3.svg
  Frontend/src/images/PlanZap logo 4.svg
Labels: GSSoC'22, Level-2

#196 Designed ideas and notes page
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/CSSComponents/ideas.css
  Frontend/src/idea.js
  Frontend/src/ideas.js
Labels: JWOC, Hard

#195 remove the error mesasge of invalid username password in register page
  Frontend/src/loginpage.js
Labels: GSSoC'22, Level-2

#201 Current Color/theme doesn't look pleasant. Hence, my small contribution to enhance the Modal colour theme
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/CSSComponents/ideas.css
  Frontend/src/calendar.js
Labels: GSSoC'22, Level-2

#200 Designed the Movies page
  Frontend/src/CSSComponents/movies.css
  Frontend/src/movies.jsx
Labels: JWOC, Hard

#207 fix: Removed all the warnings from console/VS Code
  Frontend/src/App.js
  Frontend/src/calendar.js
  Frontend/src/diary.jsx
  Frontend/src/ideas.js
  Frontend/src/movies.jsx
Labels: JWOC, Medium

#213 Fixed error in movie page
  Frontend/package-lock.json
  Frontend/src/CSSComponents/movies.css
Labels: JWOC, Medium

#215 Fixed heading in ideas page
  Frontend/src/CSSComponents/ideas.css
Labels: JWOC, Medium

#210 Add issue template Done
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/features.yaml
Labels: GSSoC'22, Level-2

#217 Changes made in task and progress section
  Frontend/package-lock.json
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
Labels: GSSoC'22, Level-2

#225 movie dashboard link feature solved
  Backend/package-lock.json
  Frontend/package-lock.json
  Frontend/src/index.css
  Frontend/src/movies.jsx
Labels: GSSoC'22, Level-2

#227 width responsive of task card
  Backend/package-lock.json
  Frontend/package-lock.json
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/calendar.js
Labels: GSSoC'22, Level-2

#228 percentage issue solved
  Frontend/src/calendar.js
Labels: GSSoC'22, Level-2

#193 code enhancement
  Frontend/package-lock.json
  Frontend/src/App.js
  Frontend/src/axiosClient.js
  Frontend/src/calendar.js
  Frontend/src/diary.jsx
  Frontend/src/ideas.js
  Frontend/src/loginpage.js
  Frontend/src/movies.jsx
Labels: GSSoC'22, Level-3

#233 Date selection in Dairy page: bug fixed
  Frontend/package-lock.json
  Frontend/src/CSSComponents/diary.css
  Frontend/src/diary.jsx
Labels: GSSoC'22, Level-1

#235 fix: Added Index in Readme.md File
  README.md
Labels: GSSoC'22, Level-2

#241 Sidebar
  Frontend/src/App.js
  Frontend/src/CSSComponents/App.css
  Frontend/src/CSSComponents/calendarstyle.css
  Frontend/src/CSSComponents/ideas.css
  Frontend/src/CSSComponents/movies.css
  Frontend/src/Components/Sidebar/index.js
  Frontend/src/Components/Sidebar/sidebar.css
  Frontend/src/booksToRead.jsx
  Frontend/src/calendar.js
  Frontend/src/ideas.js
  Frontend/src/movies.jsx
Labels: GSSoC'22, Level-2
